runtime: java11
env: standard
instance_class: F2    # F1, the "free tier", does not meet JVM memory requirements
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_instances: automatic
  max_instances: automatic
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: 10000ms
  max_concurrent_requests: 80
env_variables:
  SPRING_PROFILES_ACTIVE: production
  TZ: America/Denver
includes:
  - app-credentials.yaml
