name: Update Gradle Wrapper

on:
  schedule:
    # every week on Monday at 8am
    - cron: "0 11 * * SAT"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          target-branch: gradle-wrapper-action
